### ISSUE TITLE
Why does this project depend on phantomjs?

### ISSUE THREAD

**Issue by petejkim** [bitpay/bitcore-lib-cash#11]
This commit: https://github.com/bitpay/bitcore-lib-cash/commit/4264ccb235f1720c7d8a6787356a829034fca075 adds `phantomjs-prebuilt` as a `dependency` not a `devDependency`. The commit does not seem to utilize PhantomJS in any way. May I know why this is needed?

**Comment by gabegattis** [comment]
I think it is for browser tests. Maybe it should be a devDependency.
