### ISSUE TITLE
Could not create multisig wallet for testnet

### ISSUE THREAD

**Issue by VikasKad** [bitpay/bitcore-lib-cash#28]
I could not create mutlisig wallet for testnet using the legacy addresses.

As I checked example given in documentation its working fine but I am not able to create with legacy addresses, I got the following error message.

```
    throw new TypeError('Invalid DER format public key');
    ^

TypeError: Invalid DER format public key 
```
so the question is do **_I need to convert legacy address into DER format address,  if yes then can you provide me some example to create it, or is there any other way to create multisig wallet._**

**Comment by matiu** [comment]
to create a multisig address you need the pub key of the participants, not only their addresses (since the addresses. The addresses are a hash of the resulting script).
